language: python
python:
- '3.6'

notifications:
  email:
    on_success: never
    on_failure: always

install: pip install -r requirements.txt

before_script: pip install pytest

script: pytest --cov tests

before_deploy:
- pip install m2r
- python3 setup.py sdist bdist_wheel

deploy:
- provider: releases
  api_key:
    secure: CSYrm0aumR95Yr5LfRF+oa4hgjjPq8cg7vWfEWAqrNcmxllpp4g+cXiCndgkGOhYsHztphvMjzfSMOyZVlx6SsWfPjIOU3+5jBmqqaUIEzV78F1c0o4hFsdIgZvSb8Iy7E+qUwpKk8zHL4RtF5avUAk31VucR5K1Zzurd1OATdDKW4F4JXtnuHmQ4bFBkMRqAmCeKWP2E61QX8WTb6s2N3LTiJi5AZneJq+Hj8OisLn17h+34m9BDLu8SGuD3+7uuuZOUt0y7B5DjVA7q2wtGYtF3VRTMn0gGJNFswhlarNDeVkFWyLTaWaU3/mA0w6qODm1+R5QOjaOwZTVILnrzKdcpna0glR7DM1y3JJRnVl/tUDTKPHC3cAG1aAK4Vjy83JKQWCbvVeNmPfhNqYKudrudfGJiPO0RJP9LFTVTbonofSFhx+QBkrw6K3FNeeLnoPlGaycvS/xPlfMSQdz8C6HUNmDRXWg3wvC3iq7p2RF5sn6wjcjbgfcgxdOfwUa/K5d2TDQKrWjrpwYQctHRgqU1rammsIaKdhnyWc0GIExIeE8oqeG91GB08OIqAe+8/aq4b69XekXTx6qLVz1evUHdzTddY5i8ZYu7KjzUgSxk7mlscu/P2M8c1oScWG0Pe0Nqk5u9rZv4eLXYLxu4jINIMvrGtt6AHD2TiRJdng=
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    repo: joeblackwaslike/pyramid_bootstrap
    tags: true
  overwrite: true
- provider: pypi
  user: joeblackwaslike
  password:
    secure: "mJu1EH5wUg/WbxPp7tWy6PlNKMHaPFT1OCug0znoS4B1G+B3bxt4Zm5aDPGkTenZgcg9R//JHNnfqfRGDTDLyqx2vramSdxlvWfNFMYGsSW+/wGynk+hnoalerYm1msLpOP+8FWOwE3GeXKsQnG6R7NGfZf39y8PPnmjQwvdQm45uBUuDdtEX7SpbXP52IigZzFCRekN/2LG8DA1BMc653+bMNF7077DI9eqWw3PcfTpr2uqjui4ikZPabL8J/OOEgqOl90zhB2vVerYaaUBHFPe2/XrSHEHgN2aiXI1gVPRU3U9kW5nxtNLutZa5In051nycHG4v9x/sLjVaOxwDaFFbdttefyEtiy2UXt3o1unaL8qRPXeWA/iU3qserFSJyjYYFc13hNOT/MEmOKHaPQLC4OqVkJIeY+1SqJypMkx31I8/KFdDzxwQHr3qEvgVyWchlO+B6gJIn5Y3krEsmwvNe/KcWWdIOZO6f5PYiYS4TFU0uVy768Jy/022HgeoqjqgXILHH7b3phD715MmnpBX8MCNojXvL0nfPLPDmBqjnwNR5Xvghs0fjJOQ80t/8x0Fmk7Gpp/KFa48sw68n78oufwLRhvBWzJLHMJrTo/6V5Y/morVJ/67tJZgvPtNSx7ZJkev3p4bVGOYC1fhSBc3ALoePCrP+XP2zN6nPQ="
  on:
    tags: true
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
